services:
  unimeet-api:
    build:
      context: .
      dockerfile: src/UniMeet.API/Dockerfile
    container_name: unimeet_api_service
    ports:
      - "5000:8080"
    depends_on:
      - database
  
  database:
    image: postgres:16
    container_name: unimeet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unimeet
    ports:
      - "5432:5432"